"""Add date column to Task model

Revision ID: bbddec679a50
Revises: 
Create Date: 2025-04-11 18:44:54.115729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbddec679a50'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        from datetime import date

        batch_op.add_column(
            sa.Column('date', sa.Date(), nullable=False, server_default=sa.text(f"'{date.today().isoformat()}'"))
)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
